CREATE TABLE USUARIO (
  ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(50) NOT NULL,
  APELLIDO_PATERNO VARCHAR(50) NOT NULL,
  APELLIDO_MATERNO VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL UNIQUE,
  KEYWORD BLOB NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  SEXO VARCHAR(10) NOT NULL
);

CREATE TABLE MEDICO (
  ID_USUARIO INT PRIMARY KEY,
  CEDULA_PROFESIONAL VARCHAR(20) NOT NULL UNIQUE,

  CONSTRAINT FK_USUARIO_MEDICO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PACIENTE (
  ID_USUARIO INT PRIMARY KEY,
  ID_MEDICO INT NOT NULL,

  CONSTRAINT FK_USUARIO_PACIENTE FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
  CONSTRAINT FK_MEDICO_PACIENTE FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(ID_USUARIO)
);

CREATE TABLE TOKEN_MEDICO (
  TOKEN VARCHAR(10) PRIMARY KEY,
  ID_MEDICO INT NOT NULL,

  CONSTRAINT FK_MEDICO_TOKEN_MEDICO FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(ID_USUARIO)
);

CREATE TABLE HISTORIAL_CLINICO (
  ID_HISTORIAL_CLINICO INT AUTO_INCREMENT PRIMARY KEY,
  ID_PACIENTE INT NOT NULL,
  FECHA TIMESTAMP NOT NULL,
  PESO DOUBLE(18, 2) NOT NULL,
  TALLA DOUBLE(18, 2) NOT NULL,
  ESTATURA DOUBLE(18, 2) NOT NULL,
  IMC DOUBLE(18, 2) NOT NULL,
  LIPIDOS DOUBLE(18, 2) NOT NULL,
  CARBOHIDRATOS DOUBLE(18, 2) NOT NULL,
  PROTEINAS DOUBLE(18, 2) NOT NULL,
  AZUCAR DOUBLE(18, 2) NOT NULL,

  CONSTRAINT FK_PACIENTE_HC FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(ID_USUARIO)
);

CREATE TABLE DIETA (
  ID_DIETA INT AUTO_INCREMENT PRIMARY KEY,
  ID_PACIENTE INT NOT NULL,
  ID_MEDICO INT NOT NULL,
  DESCRIPCION VARCHAR(50) NOT NULL,
  ALIMENTOS_DISPONIBLES JSON NOT NULL,

  CONSTRAINT FK_PACIENTE_DIETA FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(ID_USUARIO),
  CONSTRAINT FK_MEDICO_DIETA FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(ID_USUARIO)
);

CREATE TABLE ALIMENTOS (
  ID_ALIMENTO INT AUTO_INCREMENT PRIMARY KEY,
  TIPO_ALIMENTO VARCHAR(45) NOT NULL,
  ALIMENTO VARCHAR(45) NOT NULL,
  CANTIDAD VARCHAR(45) NOT NULL,
  UNIDAD VARCHAR(45) NOT NULL,
  PESO_BGR INT NOT NULL,
  PESO_NGR INT NOT NULL,
  ENERGIA DOUBLE(18,2) NOT NULL,
  PROTEINA DOUBLE(18,2) NOT NULL,
  LIPIDOS DOUBLE(18,2) NOT NULL,
  CARBOHIDRATOS DOUBLE(18,2) NOT NULL,
  FIBRA_GR DOUBLE(18,2) NOT NULL,
  VITAMINA_A DOUBLE(18,2) NOT NULL,
  ACIDO_ASCORBICO DOUBLE(18,2) NOT NULL,
  ACIDO_FOLICO DOUBLE(18,2) NOT NULL,
  HIERRO_NO DOUBLE(18,2) NOT NULL,
  POTASIO DOUBLE(18,2) NOT NULL,
  AZUCAR_GR DOUBLE(18,2) NOT NULL
);
